version: '3'

services:
  ishtar-ai:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8501:8501"
    volumes:
      - .:/app
    environment:
      - PYTHONUNBUFFERED=1
      - OLLAMA_HOST=host.docker.internal
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - TAVILY_API_KEY=${TAVILY_API_KEY}
      - PINECONE_API_KEY=${PINECONE_API_KEY}
      - PINECONE_HOST=${PINECONE_HOST}
      - PINECONE_INDEX=${PINECONE_INDEX}
      - LANGCHAIN_API_KEY=${LANGCHAIN_API_KEY}
      - LANGCHAIN_PROJECT=${LANGCHAIN_PROJECT:-ishtar-ai}
      - LANGSMITH_TRACING=true
      - NEWSAPI_KEY=${NEWSAPI_KEY}
    restart: unless-stopped
    extra_hosts:
      - "host.docker.internal:host-gateway"
    command: poetry run streamlit run streamlit_app.py --server.port=8501 --server.address=0.0.0.0

volumes:
  ollama_data:
    name: ollama_data 