services:
  api:
    build:
      context: ..
      dockerfile: infra/docker/api.Dockerfile
    env_file:
      - ../.env
    ports:
      - "8000:8000"
    volumes:
      - ..:/app
    command: ["uvicorn", "apps.api.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]

  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
